### ISSUE TITLE
How the model generated?

### ISSUE THREAD

**Issue by wangyuyy** [DelinQu/Urban-Crossroads-Rolling-Shutter-Dataset#1]
Hi Delin,
This project is quite a great work! I find the work in kubric issues. As far as I know, the number of the model in kubric is only 11. So I wonder how do you generate the models in the project like cars or buildings?
Many thanks for your help.

**Comment by DelinQu** [comment]
Hi [wangyuyy](https://github.com/wangyuyy),

You can create new 3d models from https://shapenet.org/taxonomy-viewer, please refer to  the comment: https://github.com/google-research/kubric/issues/185#issuecomment-1077791677

:D

**Comment by wangyuyy** [comment]
Thanks for your rapid and helpful answer.
I also noticed that in your model, the shadows were disabled. So I wonder how to disable the shadows by kubric?

**Comment by DelinQu** [comment]
> Thanks for your rapid and helpful answer. I also noticed that in your model, the shadows were disabled. So I wonder how to disable the shadows by kubric?

It relates to the lighting in Blender. One could set an hdri environment background in the model and illuminate the entire scene. If I understand correctly, shadows still exist in my model, but because the HDRI light illuminates the majority of the area, the shadows are not very noticeable. This video might help you https://www.youtube.com/watch?v=6VBkj_I-ONk.

Specifically, in my code, I set an hdri background by [Line39](https://github.com/DelinQu/Urban-Crossroads-Rolling-Shutter-Dataset/blob/340fd637805ad998c7c4104ea6fcf7732b9b0995/rs/model.py#LL39C1-L39C99) and [Line57](https://github.com/DelinQu/Urban-Crossroads-Rolling-Shutter-Dataset/blob/340fd637805ad998c7c4104ea6fcf7732b9b0995/rs/model.py#L57).
